# Generated by Django 5.1.7 on 2025-05-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_customer_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Res_name', models.CharField(max_length=100)),
                ('Food_cat', models.CharField(max_length=200)),
                ('rating', models.FloatField()),
                ('img', models.URLField(default='https://www.foodiesfeed.com/wp-content/uploads/2023/06/burger-with-melted-cheese.jpg')),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]